---
# This file contains shared configuration for both flow and typescript
# For the typescript/flow specific setup see ./eslint/flowtype and
# ./eslint/typescript.
extends:
  - eslint:recommended
  - prettier
parser: babel-eslint
parserOptions:
  ecmaVersion: 2019
  sourceType: "module"
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
plugins:
  - node
  - prettier
  - jest
  - flowtype
env:
  es6: true
  node: true
  jest: true
globals:
  enableDeepSnapshots: true
  ruleHelpers: true
rules:
  # Core
  no-async-promise-executor:
    - off

  # Prettier
  prettier/prettier: error

  # Node
  node/no-extraneous-require:
    - error
  node/no-missing-require:
    - error
  node/no-deprecated-api:
    - error
  node/process-exit-as-throw:
    - error

  # Jest
  jest/valid-expect-in-promise:
    - error
  jest/valid-expect:
    - error
  jest/valid-describe:
    - error
  jest/prefer-to-have-length:
    - error
  jest/no-test-prefixes:
    - error
  jest/no-jest-import:
    - error
  jest/no-identical-title:
    - error
  jest/no-focused-tests:
    - error
  jest/consistent-test-it:
    - error

  # Flow
  flowtype/boolean-style: error
  flowtype/define-flow-type: error
  flowtype/no-dupe-keys: error
  flowtype/no-flow-fix-me-comments: warn
  flowtype/no-primitive-constructor-types: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/no-unused-expressions: error
  flowtype/no-weak-types:
    - error
    - any: true
      Object: true
      Function: true
  flowtype/require-exact-type: error
  flowtype/require-parameter-type:
    - error
    - excludeArrowFunctions: true
  flowtype/require-return-type:
    - error
    - always
    - excludeArrowFunctions: true
  flowtype/require-valid-file-annotation: warn
  flowtype/sort-keys:
    - error
    - asc
    - caseSensitive: true
  flowtype/type-id-match:
    - warn
    - ^([A-Z][a-z]*)+Type$
  flowtype/use-flow-type: error
