// flow-typed signature: ff58ffb39c798fab3a031be115fcb11d
// flow-typed version: <<STUB>>/amqp-connection-manager_v^2.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amqp-connection-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amqp-connection-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amqp-connection-manager/lib/AmqpConnectionManager' {
  declare module.exports: any;
}

declare module 'amqp-connection-manager/lib/ChannelWrapper' {
  declare module.exports: any;
}

declare module 'amqp-connection-manager/lib/helpers' {
  declare module.exports: any;
}

declare module 'amqp-connection-manager/lib/index' {
  declare module.exports: any;
}

declare module 'amqp-connection-manager/release.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amqp-connection-manager/lib/AmqpConnectionManager.js' {
  declare module.exports: $Exports<
    'amqp-connection-manager/lib/AmqpConnectionManager',
  >;
}
declare module 'amqp-connection-manager/lib/ChannelWrapper.js' {
  declare module.exports: $Exports<
    'amqp-connection-manager/lib/ChannelWrapper',
  >;
}
declare module 'amqp-connection-manager/lib/helpers.js' {
  declare module.exports: $Exports<'amqp-connection-manager/lib/helpers'>;
}
declare module 'amqp-connection-manager/lib/index.js' {
  declare module.exports: $Exports<'amqp-connection-manager/lib/index'>;
}
declare module 'amqp-connection-manager/release.config.js' {
  declare module.exports: $Exports<'amqp-connection-manager/release.config'>;
}
