// flow-typed signature: 9a8e6b3de3f4a29d64258b6f6300f409
// flow-typed version: <<STUB>>/upgrade_v^1.1.0/flow_v0.150.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'upgrade'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'upgrade' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'upgrade/upgrade' {
  declare module.exports: any;
}

// Filename aliases
declare module 'upgrade/upgrade.js' {
  declare module.exports: $Exports<'upgrade/upgrade'>;
}
