version: 2.1

workflows:
  version: 2

  pr_pipeline:
    jobs:
      - install
      - lint:
          requires:
            - install
      - flowtype:
          requires:
            - install
      - test:
          requires:
            - install

jobs:
  install:
    working_directory: ~/CarrotStiqs
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - save-modules

  flowtype:
    working_directory: ~/CarrotStiqs
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-modules
      - run: yarn run flow

  lint:
    working_directory: ~/CarrotStiqs
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-modules
      - run: yarn run lint

  test:
    working_directory: ~/CarrotStiqs
    docker:
      - image: circleci/node:10
    description: Start RabbitMQ container
    steps:
      - checkout
      - restore-modules
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Verify Docker Works
          command: |
            docker --version
            docker run hello-world
      - run:
          name: docker-compose up
          command: docker-compose -f docker/docker-compose.ci.yml up -d --build
      # The server isn't ready immediately, we give it 30 seconds to warm up first.
      - run: sleep 30
      - run: docker exec -i carrotstiqs bash -c "yarn run test"
      - run: pwd
      - run: docker exec -i carrotstiqs bash -c "pwd"
      - run: docker exec -i carrotstiqs bash -c "cat coverage/lcov.info" | sed "s/\/var\/CarrotStiqs/\/home\/circleci\/CarrotStiqs/g" | yarn report-coverage

commands:
  save-modules:
    description: Saves node_modules
    steps:
      - save_cache:
          key: carrotstiqs-{{ checksum "./yarn.lock" }}-{{ .Branch }}
          paths:
            - ./node_modules
  restore-modules:
    description: Saves node_modules
    steps:
      - restore_cache:
          name: Restoring node_modules
          keys:
            - carrotstiqs-{{ checksum "./yarn.lock" }}-{{ .Branch }}
            - carrotstiqs-{{ checksum "./yarn.lock" }}
