version: '2'
services:

  carrotstiqs-rabbitmq:
    container_name: carrotstiqs-rabbitmq
    image: rabbitmq:management
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
